name: Smart-CS-Agent
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - faiss-cpu==1.7.4
      - fastapi==0.109.2
      - filelock==3.20.3
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - greenlet==3.3.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.19.4
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.1.9
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-openai==0.0.8
      - langsmith==0.1.147
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - nltk==3.9.2
      - numpy==1.26.4
      - openai==1.109.1
      - orjson==3.11.5
      - packaging==23.2
      - pandas==2.1.4
      - pillow==12.1.0
      - propcache==0.4.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.46
      - starlette==0.36.3
      - sympy==1.14.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.13.3
      - torch==2.10.0
      - torchvision==0.25.0
      - tqdm==4.67.1
      - transformers==4.30.2
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.27.1
      - yarl==1.22.0
prefix: C:\Users\kyj\anaconda3\envs\Smart-CS-Agent
